-- migrations/001_create_users.sql
CREATE TABLE USERS(
	ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	USERNAME TEXT UNIQUE,
	PASSWORD_HASH TEXT,
	ROLE TEXT CHECK(ROLE IN ('COMUM', 'GERENTE')),
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	NAME TEXT,
	POSITION TEXT
);
